class ShipFromRegion < ActiveHash::Base
  self.data = [
    { id: 1, region:  '---' },
    { id: 2, region:  '北海道' },
    { id: 3, region:  '青森県' },
    { id: 4, region:  '岩手県' },
    { id: 5, region:  '宮城県' },
    { id: 6, region:  '秋田県' },
    { id: 7, region:  '山形県' },
    { id: 8, region:  '福島県' },
    { id: 9, region:  '茨城県' },
    { id: 10, region: '栃木県' },
    { id: 11, region: '群馬県' },
    { id: 12, region: '埼玉県' },
    { id: 13, region: '千葉県' },
    { id: 14, region: '東京都' },
    { id: 15, region: '神奈川県' },
    { id: 16, region: '新潟県' },
    { id: 17, region: '富山県' },
    { id: 18, region: '石川県' },
    { id: 19, region: '福井県' },
    { id: 20, region: '山梨県' },
    { id: 21, region: '長野県' },
    { id: 22, region: '岐阜県' },
    { id: 23, region: '静岡県' },
    { id: 24, region: '愛知県' },
    { id: 25, region: '三重県' },
    { id: 26, region: '滋賀県' },
    { id: 27, region: '京都府' },
    { id: 28, region: '大阪府' },
    { id: 29, region: '兵庫県' },
    { id: 30, region: '奈良県' },
    { id: 31, region: '和歌山県' },
    { id: 32, region: '鳥取県' },
    { id: 33, region: '島根県' },
    { id: 34, region: '岡山県' },
    { id: 35, region: '広島県' },
    { id: 36, region: '山口県' },
    { id: 37, region: '徳島県' },
    { id: 38, region: '香川県' },
    { id: 39, region: '愛媛県' },
    { id: 40, region: '高知県' },
    { id: 41, region: '福岡県' },
    { id: 42, region: '佐賀県' },
    { id: 43, region: '長崎県' },
    { id: 44, region: '熊本県' },
    { id: 45, region: '大分県' },
    { id: 46, region: '宮崎県' },
    { id: 47, region: '鹿児島県' },
    { id: 48, region: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
end
